### ISSUE TITLE
Seg fault when using RSA keys

### ISSUE THREAD

**Issue by SerialVelocity** [etcimon/botan#34]
Using OSX 10.12.5, ldc 1.2.0, vibe 0.8.0-beta6, botan 1.12.8, botan-math 1.0.3.

I tried to use a PKCS8 RSA key with no password. Might be related to #25.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x5fbfd410)
    frame #0: 0x0000000100738f63 raft`_D10botan_math7mp_word11word8_madd3FKG8mKxG8mmmZm at mp_word.d:869
   866                          add RAX, RCX;
   867                          adc RDX, 0;
   868                          mov carry, RDX;
-> 869                          mov [RDI+56], RAX;
   870                  }
   871                  z[0 .. 8] = ret[0..8];
   872                  return carry;
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x5fbfd410)
  * frame #0: 0x0000000100738f63 raft`_D10botan_math7mp_word11word8_madd3FKG8mKxG8mmmZm at mp_word.d:869
    frame #1: 0x0000000100738067 raft`_D10botan_math8mp_monty17bigint_monty_redcFPmxPmmmPmZv at mp_monty.d:182
    frame #2: 0x0000000100737f55 raft`_D10botan_math8mp_monty16bigint_monty_mulFPmmxPmmmxPmmmxPmmmPmZv at mp_monty.d:134
    frame #3: 0x000000010065f4e9 raft`_D5botan4math12numbertheory8def_powm23MontgomeryExponentiator7setBaseMFKxS5botan4math6bigint6bigint6BigIntZv at def_powm.d:135
    frame #4: 0x000000010066ae6e raft`_D5botan4math12numbertheory7pow_mod8PowerMod12__T7setBaseZ7setBaseMFKxS5botan4math6bigint6bigint6BigIntZv at pow_mod.d:126
    frame #5: 0x000000010066b1ef raft`_D5botan4math12numbertheory7pow_mod25FixedExponentPowerModImpl11__T6opCallZ6opCallMFKxS5botan4math6bigint6bigint6BigIntZS5botan4math6bigint6bigint6BigInt at pow_mod.d:174
    frame #6: 0x0000000100661565 raft`_D5botan4math12numbertheory7numthry12__T7isPrimeZ7isPrimeFKxS5botan4math6bigint6bigint6BigIntC5botan3rng3rng21RandomNumberGeneratormbZb at numthry.d:479
    frame #7: 0x00000001006be744 raft`_D5botan6pubkey4algo7if_algo18IFSchemePrivateKey12checkKeyImplMxFC5botan3rng3rng21RandomNumberGeneratorbZb at if_algo.d:207
    frame #8: 0x00000001006c5da0 raft`_D5botan6pubkey4algo3rsa10RSAOptions8checkKeyFxC5botan6pubkey4algo7if_algo18IFSchemePrivateKeyC5botan3rng3rng21RandomNumberGeneratorbZb at rsa.d:38
    frame #9: 0x00000001006be0c6 raft`_D5botan6pubkey4algo7if_algo18IFSchemePrivateKey8checkKeyMxFC5botan3rng3rng21RandomNumberGeneratorbZb at if_algo.d:192
    frame #10: 0x00000001006d4e52 raft`_D5botan6pubkey7pk_keys9PublicKey9loadCheckMxFC5botan3rng3rng21RandomNumberGeneratorZv at pk_keys.d:107
    frame #11: 0x00000001006bf587 raft`_D5botan6pubkey4algo7if_algo18IFSchemePrivateKey47__T6__ctorTS5botan6pubkey4algo3rsa10RSAOptionsZ6__ctorMFxS5botan6pubkey4algo3rsa10RSAOptionsC5botan3rng3rng21RandomNumberGeneratorxS8memutils10refcounted88__T10RefCountedTC5botan4asn16alg_id23AlgorithmIdentifierImplTS8memutils5utils9ThreadMemZ10RefCountedKxS8memutils6vector40__T6VectorThTS8memutils5utils9SecureMemZ6VectorZC5botan6pubkey4algo7if_algo18IFSchemePrivateKey at if_algo.d:149
    frame #12: 0x00000001006c6a62 raft`_D5botan6pubkey4algo3rsa13RSAPrivateKey6__ctorMFNcxS8memutils10refcounted88__T10RefCountedTC5botan4asn16alg_id23AlgorithmIdentifierImplTS8memutils5utils9ThreadMemZ10RefCountedKxS8memutils6vector40__T6VectorThTS8memutils5utils9SecureMemZ6VectorC5botan3rng3rng21RandomNumberGeneratorZS5botan6pubkey4algo3rsa13RSAPrivateKey at rsa.d:97
    frame #13: 0x00000001006d3b2b raft`_D5botan6pubkey7pk_algs14makePrivateKeyFKxS8memutils10refcounted88__T10RefCountedTC5botan4asn16alg_id23AlgorithmIdentifierImplTS8memutils5utils9ThreadMemZ10RefCountedKxS8memutils6vector40__T6VectorThTS8memutils5utils9SecureMemZ6VectorC5botan3rng3rng21RandomNumberGeneratorZC5botan6pubkey7pk_keys10PrivateKey at pk_algs.d:102
    frame #14: 0x00000001006d6658 raft`_D5botan6pubkey5pkcs87loadKeyFS8memutils10refcounted81__T10RefCountedTC5botan7filters8data_src14DataSourceImplTS8memutils5utils6AppMemZ10RefCountedC5botan3rng3rng21RandomNumberGeneratorDFZAyaZC5botan6pubkey7pk_keys10PrivateKey at pkcs8.d:155
    frame #15: 0x00000001006d7f37 raft`_D5botan6pubkey5pkcs87loadKeyFxAyaC5botan3rng3rng21RandomNumberGeneratorDFZAyaZC5botan6pubkey7pk_keys10PrivateKey at pkcs8.d:186
    frame #16: 0x00000001006d8016 raft`_D5botan6pubkey5pkcs87loadKeyFxAyaC5botan3rng3rng21RandomNumberGeneratorxAyaZC5botan6pubkey7pk_keys10PrivateKey at pkcs8.d:201
    frame #17: 0x00000001002f215a raft`_D4vibe6stream5botan15BotanTLSContext17usePrivateKeyFileMFAyaZ9__lambda2MFNeZC5botan6pubkey7pk_keys10PrivateKey at botan.d:456
    frame #18: 0x00000001002f20b7 raft`_D4vibe6stream5botan15BotanTLSContext17usePrivateKeyFileMFNfAyaZv at botan.d:456
    frame #19: 0x000000010001c5d7 raft`_Dmain at app.d:46
    frame #20: 0x0000000100a1091f raft`_D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv + 15
    frame #21: 0x0000000100a10864 raft`_D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFMDFZvZv + 20
    frame #22: 0x0000000100a1078d raft`_d_run_main + 461
    frame #23: 0x00000001000b3a45 raft`main at __entrypoint.d:8
    frame #24: 0x00007fffd4d17235 libdyld.dylib`start + 1
    frame #25: 0x00007fffd4d17235 libdyld.dylib`start + 1
```

**Comment by etcimon** [comment]
Seems to be related to the asm parser in ldc. I think it could be fixed by using the regular code path, the assembly code should be in a versioned segment

**Comment by SerialVelocity** [comment]
Unfortunately, because of #14, I can't compile it with DMD.

**Comment by etcimon** [comment]
which error is it? there were 2 in that issue

**Comment by SerialVelocity** [comment]
When trying to use DMD, I get:
```
ld: in ../../../.dub/packages/botan-1.12.8/botan/.dub/build/full-release-posix.osx-x86_64-dmd_2074-FD6A03E6A182FBDA0BF4B5E2C70BD89D/libbotan_base.a(unique_3f32_3b6.o), in section __TEXT,__textcoal_nt reloc 0: symbol index out of range for architecture x86_64
```

Afaik, the two errors are the same in that ticket.

**Comment by SerialVelocity** [comment]
I tried disabling asm but then hres_timer hits an `static assert(0)` because asm is disabled

**Comment by etcimon** [comment]
You can delete that part of the code at mp_word.d:869, you`ll find a code path without asm if you edit it. In the meantime, I'll try and figure out if it's hitting a symbol limit, maybe disabling a few ciphers in the "Versions" tags of the dub file would be a good workaround

**Comment by SerialVelocity** [comment]
Any idea which versions are most likely to be the big offenders? I really just need ciphers that allow me to use http/2 with vibe.

**Comment by etcimon** [comment]
I need to start testing it out a bit, on my end I haven't had issues with OSX but I'm still on 2.071

**Comment by etcimon** [comment]
The linker error in Mac should be fixed now.

**Comment by SerialVelocity** [comment]
Thanks! I'll give it a go in the next few weeks.

**Comment by katafrakt** [comment]
@etcimon I'm afraid the error is still there:

```
Linking...
ld: in ../../../.dub/packages/botan-1.12.9/botan/.dub/build/full-debug-posix.osx-x86_64-dmd_2075-64FB6DC645B165220CB51902EF5F2222/libbotan.a(unique_4a15_3b6.o), in section __TEXT,__textcoal_nt reloc 2: symbol index out of range for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
dmd failed with exit code 1.
```

I tried both latest version and master. Oddly, botan tests seem to run (I didn't run the whole suite though).

**Comment by etcimon** [comment]
Have you run the master branch?

**Comment by katafrakt** [comment]
Yes

**Comment by katafrakt** [comment]
To avoid confusion: I tried both `master` and `1.12.7` of botan with `DMD64 D Compiler v2.075.0`.
